### ISSUE TITLE
Default import of any component throwing error

### ISSUE THREAD

**Issue by sanju-developer** [JeremyRH/storybook-addon-code-editor#18]
Hey @JeremyRH 

Can you please help me why I'm getting error while importing my 3rd party/inhouse-project common component as default.

For example:
![image](https://user-images.githubusercontent.com/45697130/230016212-249a21fc-153a-4b41-8240-b054af181fc9.png)

I'm tryign to import `TextField` as default import but it ends up with an error  

`TypeError: Failed to resolve module specifier "@mui/material/TextField"`

One question just in general: Does this library will be having support in future?

**Comment by JeremyRH** [comment]
Every import specifier needs to be defined in `availableImports`. Here is how you would do it:
```js
availableImports: {
  '@mui/material/TextField': { default: MUI.TextField, __esModule: true },
},
```
The `__esModule` part is needed for default exports because the import statements get transformed to CommonJS. I'll try to make this easier to configure someday.

> Does this library will be having support in future?

I'll try to support it for a year and if it doesn't get popular, I'll stop. The license is MIT so hopefully if I do stop maintaining it, someone else can fork it and maintain it. There are other options but I always ran into issues with them.

**Comment by sanju-developer** [comment]
Hey @JeremyRH , Thanks for support closing this ticket. 

Do not remove this as a library as I'm using it's one of it' version in my project :)

**Comment by JeremyRH** [comment]
I wont remove it but if I do stop working on it, I will update the README and say this project is in "security-fixes-only" mode and it might not work for the next major version of storybook. That reminds me, I need to make sure this works with storybook 7.
