### ISSUE TITLE
Multiple React imports error

### ISSUE THREAD

**Issue by Sarthik-mehta** [JeremyRH/storybook-addon-code-editor#22]
Hey @JeremyRH 

When code provided to playground contains an import statement like this, ` import React, { useState } from 'react'; ` then it throws the following error: 
![addon-code-editor error](https://github.com/JeremyRH/storybook-addon-code-editor/assets/65113721/4eb5672b-8f79-41f6-8d61-35d35927d0d1)

It works fine if there are two separate import lines ` import React from 'react'; ` and ` import { useState } from 'react'; `.  Could you please share your thoughts on why it's giving such an error?

**Comment by JeremyRH** [comment]
Looks like a bug. `import * as React from 'react';` is added if [this regexp](https://github.com/JeremyRH/storybook-addon-code-editor/blob/c7aabd3c01000e5a453af7e9eca207eb9d2ab206/src/index.tsx#L16) does not match anything. It doesn't take into account the `default, { named }` import syntax.

The proper way would be to use the AST rather than regexp. The easy fix is to detect `React` as an identifier by changing the regexp to `/import +(\* +as +)?React[, ]/`. I'll do that.
