### ISSUE TITLE
Does this addon support Angular >=14

### ISSUE THREAD

**Issue by AndroPlus** [JeremyRH/storybook-addon-code-editor#29]
I saw in documentation..  it supports only react and ts. can you please confirm me on angular.
If this addon also supports angular it will super helpful to us.

**Comment by JeremyRH** [comment]
Sorry, it only works with React right now. I could make the code transformations configurable so any framework or library will work, but that will take some effort.

**Comment by kenisteward** [comment]
@JeremyRH What is the capacity needed for doing the work to support Angular?  I'm considering contributing this but not sure if I understand the full scope

**Comment by JeremyRH** [comment]
@kenisteward My initial instincts tell me, you would need to start from the place code is transformed after it's typed into the editor and `eval`d here:
https://github.com/JeremyRH/storybook-addon-code-editor/blob/959bdd0bb2bc9d8791cff12424ad232e4b29bfae/src/evalModule.ts
This should be made library and framework agnostic. Anything React related would be passed in as an argument.

The [`Preview` component](https://github.com/JeremyRH/storybook-addon-code-editor/blob/959bdd0bb2bc9d8791cff12424ad232e4b29bfae/src/Preview.tsx) calls the function above and uses the default export as a React component. That would have to change.

Storybook plugins use React components to display things. This is fine because a React component can wrap an Angular component. This does mean the `Preview` component needs some generic way of wrapping whatever the default export of the evaled code produces. Maybe the `Preview` component can accept a function prop for this.

These are my thoughts but here's probably something I'm not taking into account.

**Comment by kenisteward** [comment]
@JeremyRH thanks so much for responding!

Hopefully I can absorb the mental model of the changes quickly enough to have a rough sketch locally. I maintain angular libraries that build forms using json schema and am hoping to use this to allow for intellisense based json input authoring for component inputs.

**Comment by JeremyRH** [comment]
That sounds interesting! So the user enters JSON in the editor and a form is displayed based on this JSON? And you would like intellisense when the user is typing this JSON?

Side note: I thought about this issue more. Allowing a fully custom `Preview` component might solve this in a cleaner way than trying to make the `Preview` component generic.
