### ISSUE TITLE
Docs tab is not visible when using live code editor

### ISSUE THREAD

**Issue by Heet-Bhalodiya** [JeremyRH/storybook-addon-code-editor#6]
Currently, I am in the process of implementing a code editor addon in my Next.js project. While the live code editor has been successfully implemented, it has come to my attention that the `Docs` tab does not appear in any story where the live code editor has been implemented. Conversely, in stories where the code editor has not been implemented, the doc tab functions as intended. 

For your reference, here are screenshots:

![image](https://user-images.githubusercontent.com/100203834/225902790-cc069a8b-23c7-4a03-a0f9-4f3d7401d167.png)

![image](https://user-images.githubusercontent.com/100203834/225903237-89348343-d772-4ed1-b851-32271fe497ec.png)

**Comment by JeremyRH** [comment]
Thanks for the feedback. It was intentionally hidden because the "Show code" button showed the preview component, not the editor source. See here:

![Screenshot 2023-03-19 at 12 07 37 PM](https://user-images.githubusercontent.com/12418905/226203088-82869051-570f-4137-ae35-dc918a8582bb.png)

I didn't think this was a good user experience and decided to hide the docs panel by default.
But now I've found a way to show the editor source so the docs panel is not hidden anymore. Update to version `1.2.0` to get this feature.
